kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: bookstore-admin
  namespace: bookstore
subjects:
- kind: ServiceAccount
  name: ns-reconciler-bookstore
  namespace: config-management-system
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io