# root/crd-fulfillment.yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: fulfillmentcenters.acme.com
spec:
  group: acme.com
  versions:
    - name: v1
      served: true
      storage: false
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
              - address
              properties:
                address:
                  type: string
    - name: v2
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
              - address
              properties:
                address:
                  type: string
    - name: v3
      served: true
      storage: false
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
              - address
              properties:
                address:
                  type: string
                city:
                  type: string
  scope: Namespaced
  names:
    plural: fulfillmentcenters
    singular: fulfillmentcenter
    kind: FulfillmentCenter
